### PR TITLE
Add Microsoft vendor to Jambonz Webapp

### PR DESCRIPTION
**Pull request by kitajchuk**

### CODE REVIEW

**Comment by kitajchuk** [comment]
@davehorton Second commit adds the MS vendor to the Application form. I believe I've got the data correct but please verify that everything looks correct for these changes please 👍

**Comment by davehorton** [comment]
I think the functionality looks good, but here are a few notes on the UI:

2) The prompt about signaling IPs now show up on the Speech credentials page:

image

2) When adding a speech credential, if you select Microsoft you no longer get the checkboxes "use for tts", "use for stt".  This is probably why the credentials never fail, because we never test on the server side since the creds are not enabled for either service.

image

3) On the Add/Edit Application page, if you select Microsoft as Speech Synthesis vendor, it seems to punch the voice dropdown out through the right edge of the page

image

**Comment by kitajchuk** [comment]
@davehorton I fixed those 3 things. I squashed this branch so as long as things look good I think we're good 👍

**Comment by davehorton** [comment]
Looks good.  Only one issue left -- the speech form is still showing the text that should only appear on the Carrier panel

image

**Comment by kitajchuk** [comment]
@davehorton Okay—pushed a commit to fix that. I guess I had removed the `Sbcs` copy from the Speech Services list page but I missed it on the actual form—doh!

**Pull request merged**
