### PR TITLE
Application page for refresh branch

### PR DESCRIPTION
**Pull request by khanghugo**
#70 

For now, it is barely working. I know why but I can't really bring up the solution for that. My hypothesis is I have no idea how to do async so the pulled array is empty, aka not waiting for the promise. 

I am not sure what is the more correct way to do those things so I do need some guidance on this.

Besides that, I have tested with some hacks and it works with the backend nicely, as far as checking whether the entries get in, get out, and get deleted.

### CODE REVIEW

**Comment by khanghugo** [comment]
It seems like I just messed up the rebase... I guess I can redo this.

**Comment by khanghugo** [comment]
okay I am going to nuke these commits and work back normally

**Comment by khanghugo** [comment]
Okay, I think this is all?

**Comment by kitajchuk** [comment]
> It seems like I just messed up the rebase... I guess I can redo this.

You should be able to just do `git pull origin refresh --rebase` for this. I wouldn’t imagine you would have conflicts. Also you’ll need to rename your branch so the PR checks will run. Remove the `origin`. You can just do `git branch -M refresh/applications` for this. But you’ll have to push the branch and open a new PR for it.

**Comment by kitajchuk** [comment]
@khanghugo I just pushed some changes for the file-upload component. This was a history reset on `refresh` because I squashed some commits down. If you notice my earlier comment about rebasing and PR branch naming you'll want to do the following:

- Rename your branch to simply `refresh/applications`
- Rebase from `refresh` base -- `git pull origin refresh --rebase`
- Hopefully you don't have any conflicts but if you do have them in files you didn't actually edit just take the new code
- Push your new branch and open a PR for it and then the GitHub actions `pr-checks` should run correctly

**Comment by khanghugo** [comment]
Haha, I have no idea how Git works. Let me try that again and see. Yesterday rebase was fine, finally and thankfully. The rebase is from the latest commit of `refresh` at the time and the only conflict was in the file I was working on.

Let me figure out how to do what I really want to do with Git stuff and see if it is what I want.

**Comment by khanghugo** [comment]
Let me nuke this PR because it will make things easier.

**Comment by kitajchuk** [comment]
> Haha, I have no idea how Git works. Let me try that again and see. Yesterday rebase was fine, finally and thankfully. The rebase is from the latest commit of `refresh` at the time and the only conflict was in the file I was working on.
> 
> Let me figure out how to do what I really want to do with Git stuff and see if it is what I want.

No worries. Git takes time to get comfortable with and you'll never master it lol. I think you should be able to rebase okay now since I removed the conflict from that specific file in question. You may also be able to do this in order to avoid conflicts:

- Checkout the base `refresh` branch and do a fresh pull to get the latest
- Cut a new branch for the new PR: `git checkout -b refresh-applications`
- Cherry pick just your commits from the old branch: `git cherry-pick {commit sha}`

This could possibly be easier on you overall 🤔

**Pull request closed without merging**
