### PR TITLE
Fix speech form dropdown menu reference

### PR DESCRIPTION
**Pull request by khanghugo**

### CODE REVIEW

**Comment by davehorton** [comment]
looks good.  Could you also update the list of Azure speech regions to the latest, as you did in jambonz-webapp-comm recently?

**Comment by khanghugo** [comment]
It has been approved in this commit https://github.com/jambonz/jambonz-webapp/commit/013681e7ebe0f7a03de080dd23dda0392f9c4c9b of jambonz-webapp. 

I simply pulled the file from jambonz-webapp to jambonz-webapp-com.

**Comment by davehorton** [comment]
weird, when I test this PR I see this which does not look like the latest.  What do you see?

image

**Comment by khanghugo** [comment]
I think you forgot to pull from the repo? The changes are there in the repo.

**Comment by davehorton** [comment]
I think you did not branch from the latest main.  Can you update your PR?

image

**Comment by khanghugo** [comment]
Okay, it seems like it should work now. My silly mistake.

**Review by davehorton — APPROVED** [review]

**Pull request merged**
