### PR TITLE
Jaeger Typescript interfaces

### PR DESCRIPTION
**Pull request by ajukes**
Define Jaeger Types in preparation for Jaeger Tracing API implementation

### CODE REVIEW

**Comment by ajukes** [comment]
Thought about placing this file under ./vendors but that seems to relate to TTS/SST only.

**Comment by davehorton** [comment]
are you planning on implementing the UI @ajukes ?  If so I would just like to keep all that work on this branch until it is ready for review and merge

**Comment by ajukes** [comment]
With some guidance from @xquanluu and with your blessing I can give it a go? This branch as in `callable-ltd:feature/jaeger-types` ?

**Comment by davehorton** [comment]
yes this branch here.  I dont think its worth merging the types without the UI that uses them

**Comment by ajukes** [comment]
closing this pr. Created a clean branch for a complete implementation of ui

**Pull request closed without merging**
