### PR TITLE
Fix issue where is_active user & force_change cannot be deactivated

### PR DESCRIPTION
**Pull request by EgleHelms**
Related PR in jambonz-api-server: https://github.com/jambonz/jambonz-api-server/pull/95

We allow falsy values to be sent and updated. Before api was updating only a truthy value.

### CODE REVIEW

**Comment by EgleHelms** [comment]
I have also fixed the issue where SP scope user did not see API keys section in SP settings.

**Review by davehorton — APPROVED** [review]

**Comment by davehorton** [comment]
@kitajchuk if you have a chance to review this and the other open PRs today that would be great, otherwise I will go ahead merge them

**Comment by EgleHelms** [comment]
@davehorton @kitajchuk this is also a small change that could be merged.

To test try deactivating a user.
To test SP API keys create an SP user, login in and search for SP Apikeys in the settings.

**Comment by davehorton** [comment]
@EgleHelms can you rebase to latest?

**Pull request merged**
