### PR TITLE
feat: Lcr

### PR DESCRIPTION
**Pull request by xquanluu**

### CODE REVIEW

**Comment by xquanluu** [comment]
#236

**Comment by xquanluu** [comment]
Hi @davehorton  I have fixed all your comments.

**Comment by davehorton** [comment]
As admin user, I added a lcr table with two routes/digit patterns.  I then used the up arrow to move one of them to the top, saved and came back in.  Now that route has been duplicated and there are 3 routes instead of 2.  In the image below, I entered the pattern `/{10}d/` once, saved and moved it up, saved again, exited and came back and now it has been duplicated

image

**Comment by davehorton** [comment]
The listview looks like this currently
image
To the route of "default account" I would like to show the number of routes, ie "12 routes"

**Comment by xquanluu** [comment]
Screenshot 2023-04-27 at 11 17 27
Hi @davehorton 
I cannot reproduce the issue you mentioned about the dupplication, I have tried multiple times. Can you please try again.

I have edit the list view to have number of routes as requested.

**Comment by davehorton** [comment]
After adding 5 rows, the plus button disappears and I can not add any more.  The requirement is to be able to add essentially an unlimited number of rows.
image

**Comment by davehorton** [comment]
Additionally, I think am not satisfied with the "up" button method of changing the order of the rows.  Could you please see if you can implement drag-and-drop to change the order, instead of using a button.  Perhaps [this react code example](https://react-table-v7.tanstack.com/docs/examples/row-dnd) is useful?

**Comment by xquanluu** [comment]
Start implementing drag and drop inside a scrollable area.

**Comment by xquanluu** [comment]
Hi @davehorton I finished Drag and Drop for LCR route,  unblock unlimited routes, Please help me to review it again.

**Comment by davehorton** [comment]
No, this isn't quite what I had in mind.
image

You can see in the screen shot that *all* rows have a box shadow.  What I would like to see is that *no* rows have box shadow *except* when mouseover a row.  That is, only when mousing over a row should I see it have a box shadow

**Comment by xanhnguyen** [comment]
Screenshot 2023-05-05 at 06 20 53
Hi @davehorton I fixed the shadow box and add transform event that when mouse over, will bring the row up a bit

**Comment by xquanluu** [comment]
Screenshot 2023-05-05 at 06 20 53
I fixed the shadow box and add transform event that when mouse over, will bring the row up a bit

**Review by davehorton — APPROVED** [review]

**Pull request merged**
