### PR TITLE
Fix issue #57

### PR DESCRIPTION
**Pull request by khanghugo**

### CODE REVIEW

**Comment by davehorton** [comment]
OK that looks good.

However, there is another issue I would like you to fix.

Now, I can add a new SP and then I can add a Carrier and see it under that SP.  That's great.

However, if right after that, I add a new phone number under that SP, associate it with the new SP, and leave the account blank (because I have not added an account under that SP), the phone number gets added under the 'default' SP.

Could you look into fixing that as well, and push the changes to this PR

**Comment by khanghugo** [comment]
Hmmm. I see. So what I think might be the fix is to create a new account for that phone number when there is no account. If I do that then should there also be an option to create a new account associated with the phone number in the phone number tab. 

On the other hand, we can create a default account for a new SP and that phone number will be under that default account.

This is an edge case that I think create a default account is the most foolproof.

**Comment by davehorton** [comment]
No, please do not create a new account.

If you look at the POST request with the new phone number, you will the problem is that for some reason it is including an account sid, even though you did not specify one

You should be able to add a phone number as long as you have a carrier.  Associating a phone number to an account is purely optional

**Comment by khanghugo** [comment]
I see where it is now.
https://github.com/jambonz/jambonz-webapp/blob/bb335d08387d20706ec0308f3cfd4cf098563ea1/src/components/forms/PhoneNumberForm.js#L51

From here, the API request get all of the available information, including ones from other SP. What I can do here is to filter out the SPs that don's match with the current SP we are looking at.

**Review by davehorton — APPROVED** [review]

**Pull request merged**
