### PR TITLE
Issue #170: Fix bug with bad user reference in internal accounts page

### PR DESCRIPTION
**Pull request by kitajchuk**

### CODE REVIEW

**Comment by kitajchuk** [comment]
@davehorton I sure enough did replicate the bug locally by adding a token in my storage that was NOT a JWT. But, the real issue here was using a bad reference to the `user` in a component. We need to always pull the current user from the `store` so that is what the root cause of the bug was.

**Review by davehorton — APPROVED** [review]

**Comment by EgleHelms** [comment]
@kitajchuk this fix makes the bug of logging out as an account user and then logging in as admin throw this error since the state is not updated in time. I thought this was actually agreed on in the Scoping PR we merged.

image

**Comment by EgleHelms** [comment]
Maybe a fix here could be not redirecting to something that is accessible to all. Like "Applications"?

**Comment by davehorton** [comment]
"state not updated in time" sounds like a strange race condition we ought to fix.  Once you are logged out, why is there any state at all kept?

**Comment by kitajchuk** [comment]
@davehorton @EgleHelms This PR fixes the issue of logging out and switching users: https://github.com/jambonz/jambonz-webapp/pull/174

**Pull request merged**
