### PR TITLE
feat/940: Removed last_used column from speech services

### PR DESCRIPTION
**Pull request by rammohan-y**
https://github.com/jambonz/jambonz-feature-server/issues/940

Removed the last used column, please see attached picture

image

### CODE REVIEW

**Review by davehorton — APPROVED** [review]

**Comment by davehorton** [comment]
@xquanluu please review and merge if looks good to you

**Comment by rammohanyadavalli** [comment]
@xquanluu please merge this PR after you feel the changes are good

**Comment by davehorton** [comment]
rebase to main please

**Comment by rammohan-y** [comment]
Rebased @davehorton

**Pull request merged**
