### PR TITLE
elevenlabs new model and options

### PR DESCRIPTION
**Pull request by xquanluu**
https://github.com/jambonz/jambonz-feature-server/issues/541

### CODE REVIEW

**Comment by davehorton** [comment]
- change wording to "Beautify"
- can we add an anchor tag with label "Docs" that goes to the url https://elevenlabs.io/docs/api-reference/streaming ?  I think if we align it horizontally with "Extra options" but push it to the right so that it above "Beautify" that would be good

**Comment by xquanluu** [comment]
Screenshot 2023-11-30 at 22 09 08

**Comment by xquanluu** [comment]
Extra Options is header of CheckZone, modify it is quite hard, so I put Docs and Beauty at the same row

**Comment by davehorton** [comment]
@xquanluu can you deploy to jambonz.me for testing?  In the screen shot "Docs" and "Beautify" seem like they are not quite aligned horizontally

**Review by davehorton — APPROVED** [review]

**Pull request merged**
